Feature/canvas map
LB31/HikingForNerds pull request #134
Opened 2020-01-18 16:49 UTC by dephiloper

2020-01-19 13:11 UTC, jakubprogramming requested changes
Ok your example looks good, but why did you not include it inside the route list? 
The way it is now it does not really add any value to our app. We could merge this just to have the code available, but imo why not include it right away?

2020-01-19 13:20 UTC, dephiloper commented
> Ok your example looks good, but why did you not include it inside the route list?
> The way it is now it does not really add any value to our app. We could merge this just to have the code available, but imo why not include it right away?
This is not the task of this feature. The integration into the list will be done by @mayo-s.

2020-01-20 10:50 UTC, mayo-s approved these changes

2020-01-20 10:51 UTC, mayo-s commented
Reviewed it and also merged it into route_list.

2020-01-20 18:41 UTC, jakubprogramming approved these changes

2020-01-20 18:42 UTC, merged