Feature/mapbox draw route
LB31/HikingForNerds pull request #52
Opened 2019-12-04 13:10 UTC by jakubprogramming

This merge request functionality necessary to draw routes and switch them on button press.
Functionality that is not finished implementing or not needed any longer has been deactivated/removed.

2019-12-05 18:34 UTC, dephiloper requested changes
Please merge the current dev in this branch. Remove the unused comments and resolve the conflicts if you can comprehend them and are of the opinion that they make sense. Especially loading the route after the map was successfully created.

2019-12-05 18:34 UTC, dephiloper commented on ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
> +<?xml version="1.0" encoding="UTF-8"?>
please add this file to gitignore
already resolved by merging Dev into this branch.

2019-12-05 18:34 UTC, dephiloper commented on lib/components/hikingmapbox.dart
> +      //print("DISTANCE $distanceToCurrentLocation");
remove comment

2019-12-05 18:34 UTC, dephiloper commented on lib/components/hikingmapbox.dart
> +        //print("i=" + i.toString() + " latlng = " + latLng.toString() + " length = " + passedRoute.length.toString());
remove comment

2019-12-05 18:34 UTC, dephiloper commented on lib/components/hikingmapbox.dart
> +      //print("DISTANCE $distanceToCurrentLocation");
remove print

2019-12-05 18:34 UTC, dephiloper commented on lib/components/hikingmapbox.dart
> +    int numberOfNodesToUpdate = _route.length > 5 ? 5 : _route.length;
introduce const for 5

2019-12-05 18:34 UTC, dephiloper commented on lib/services/osmdata.dart
> +    //      print("Initial Heading: " + initialHeading.toString());
remove comments

2019-12-05 18:34 UTC, dephiloper commented on pubspec.lock
>        url: "https://pub.dartlang.org"
ignore this

2019-12-05 18:34 UTC, dephiloper commented on lib/components/hikingmapbox.dart
> +        //print("i=" + i.toString() + " latlng = " + latLng.toString() + " length = " + passedRoute.length.toString());
remove comment

2019-12-05 18:34 UTC, dephiloper commented on lib/components/hikingmapbox.dart
> +            updateCurrentLocationOnChange();
when the map is created you can receive a callback where you start tasks like:
```
getCurrentLocation()
initRoutes()
updateCurrentLocationOnChange()
```

This callback is already implemented see line 445 in the file onMapCreated.

2019-12-05 18:34 UTC, dephiloper commented on android/build.gradle
> +}
i think this should be reverted

2019-12-10 10:40 UTC, jakubprogramming commented
Ok is done

2019-12-10 10:49 UTC, dephiloper reviewed
done

2019-12-10 11:36 UTC, merged