Feature/height chart
LB31/HikingForNerds pull request #86
Opened 2019-12-18 14:15 UTC by LB31

- Chart needs routes to be tested
- ElevationGetter needs to be awaited when used
- ElevationChart currently shows the amount of nodes instead of the route distance on the x-axis

2019-12-19 13:52 UTC, LB31 commented
- added descriptions for axes
- made descriptions and chart interaction optional
- the x-axis shows know the actual distance

2019-12-20 00:03 UTC, dephiloper requested changes
There are some minor and some major issues that you should consider to change. Especially the index should be removed imo and you should set the route and an callback function as constructor params.

2019-12-20 00:03 UTC, dephiloper commented on .flutter-plugins-dependencies
> +{"_info":"// This is a generated file; do not edit or check into version control.","dependencyGraph":[{"name":"esys_flutter_share","dependencies":["path_provider"]},{"name":"geocoder","dependencies":
.flutter-plugins-dependencies should be ignored see line 47. https://github.com/flutter/flutter/blob/master/.gitignore

please put this into the gitignore

2019-12-20 00:03 UTC, dephiloper commented on android/gradle.properties
> +android.enableR8=true
what does this option do? Is this really necessary?

2019-12-20 00:03 UTC, dephiloper commented on lib/pages/home.dart
> +  static bool chartIsHere = false;
this is only used for an print so I guess that could be removed

2019-12-20 00:03 UTC, dephiloper commented on lib/pages/home.dart
> +    bool done = false;
done gets set but is never used, is there a reason to have this variable?

2019-12-20 00:03 UTC, dephiloper commented on lib/pages/home.dart
> +      route.elevations = value;
value is a weak name for this parameter here, elevations would be better

2019-12-20 00:03 UTC, dephiloper commented on lib/pages/home.dart
> +                HikingRoute mockRoute = route;
declarated mockroute only once at the top of this file and use it everywhere, this copy isn't really needed

2019-12-20 00:03 UTC, dephiloper commented on lib/pages/settings.dart
> +    print("CHART IS HERE2 " + Home.chartIsHere.toString());
please remove the print
why is the settings page created in this branch when the branch is for the height chart only?

2019-12-20 00:03 UTC, dephiloper commented on lib/services/ElevationChart.dart
> +class ElevationChart extends StatelessWidget {
naming the class ElevationChart is fine but the file should be not be named in CamelCase
right naming would be snake_case 
see: https://dart.dev/guides/language/effective-dart/style

furthermore elevationchart is an widget and should be inside compontents not under service

2019-12-20 00:03 UTC, dephiloper commented on lib/services/ElevationChart.dart
> +  int index;
Flutter marks here that you have specified that this widget is stateless, but then on the other hand you have defined an 'index' here which gets modified and stored while using the chart. Therefore this widget should have an state (extending from StatefulWidget).

Probably the index variable isn't needed at all, if this is true delete it and let the widget stay stateless.

2019-12-20 00:03 UTC, dephiloper commented on lib/services/ElevationChart.dart
> +  final List<charts.Series> seriesList;
why should the elevation chart get an list of series handed over? shouldn't this be an route object?

2019-12-20 00:03 UTC, dephiloper commented on lib/services/ElevationChart.dart
> +  static List<charts.Series<RouteChart, double>> _createData(HikingRoute route,
i guess this is only for testing? if not change naming of the variables: lastX, x, sales, 

I think to test the chart properly you should only have to pass the mockroute into it, no need for creating additional mock data in the widget.

2019-12-20 00:03 UTC, dephiloper commented on lib/services/ElevationChart.dart
> +  ElevationChart(this.seriesList, {this.interactive, this.withLabels});
the callback function is missing here for us to insert as parameter.

when creating an elevation chart there should be the option to set an callback as parameter which gets called when the user drags over the points of the elevation chart. You have created an function inside this widget but it does not call the callback function therefore there is no access from outside the widget.

parent_page ---- callback function ----> elevation_chart

elevation_chart->user_drag_event() { call callback function with index as parameter }

2019-12-20 00:03 UTC, dephiloper commented on lib/services/osmdata.dart
> +  static double getDistance(nodeA, nodeB){
why is the type removed here. This should not be necessary anymore.

2019-12-20 00:03 UTC, dephiloper commented on lib/services/route.dart
> +  HikingRoute(this.path, this.totalLength,[this.pointsOfInterest]);
why not adding the elevation to as optional parameter to the constructor

2019-12-20 00:03 UTC, dephiloper commented on lib/services/ElevationChart.dart
> +    for (var i = 0; i < route.elevations.length; i++) {
types are prefered, we suggested in one meeting to use them

2019-12-20 00:03 UTC, dephiloper commented on lib/services/elevationQuery.dart
> +    for (var i = 0; i < path.length; i++) {
types are prefered, we suggested in one meeting to use them

2019-12-20 00:03 UTC, dephiloper commented on lib/services/elevationQuery.dart
> +        var response = await http.get(currentURL);
types are prefered, we suggested in one meeting to use them

2019-12-20 00:03 UTC, dephiloper commented on pubspec.yaml
> +  fl_chart: ^0.6.0
fl_chart is not needed

2019-12-20 00:03 UTC, dephiloper commented on lib/services/ElevationChart.dart
> +  factory ElevationChart.withData(HikingRoute route,
the factory is one way, but i think the more intuitve way would be to set the route via the constructor (@required) and use the route data inside build to create the chart correctly

2019-12-20 17:02 UTC, LB31 commented on android/gradle.properties
> +android.enableR8=true
https://android-developers.googleblog.com/2018/11/r8-new-code-shrinker-from-google-is.html

seems to be a code shrinking feature for Android builds. Was inserted automatically, but sounds not wrong for me.

2019-12-20 17:07 UTC, LB31 commented on lib/pages/home.dart
> +    bool done = false;
This one was experimental. I will remove it.
In the future we need to see how code parts that are pulling elevations should handle the waiting without disturbing the rest of the flow.

2019-12-21 13:51 UTC, LB31 commented on lib/services/ElevationChart.dart
> +  ElevationChart(this.seriesList, {this.interactive, this.withLabels});
see onSelectionChanged parameter in the next push

2019-12-21 14:00 UTC, LB31 commented
@dephiloper thank you for your detailed review. The issues should be solved now.

2019-12-22 15:53 UTC, dephiloper commented on android/gradle.properties
> +android.enableR8=true
alright

2019-12-23 12:08 UTC, dephiloper approved these changes

2019-12-23 12:08 UTC, merged